
[env]
TERM = "xterm-256color"

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[general]
import = [
  "~/.config/alacritty/themes/themes/dark_pride.toml"
  #"~/.config/alacritty/theme.toml"
]
